.TH CAPI4HYLAFAXCONFIG "1" "" "capi4hylafaxconfig" "System Commands"
.SH NAME
capi4hylafaxconfig \- generate a configuration for capi4hylafax.
.SH SYNOPSIS
.B capi4hylafaxconfig
.SH DESCRIPTION
Interactively generate a configuration for capi4hylafax.
.SH SEE ALSO
c2send(1), c2recv(1), hylafax(5). /usr/share/doc/capi4hylafax/README.html.
